version: 2

models:
  - name: job_postings
    description: |
      The `job_postings` model joins transformed fields and untransformed source fields.
    columns:
      - name: id
        description: |
          The primary key for job_postings.
        tests:
          - unique
          - not_null
      - name: url
        description: |
          The url of the job posting.
        tests:
          - unique
          - not_null
      - name: title
        description: |
          The title of the job.
        tests:
          - not_null
      - name: company
        description: |
          The company of the job.
        tests:
          - not_null
      - name: location
        description: |
          The location of the job.
      - name: contract
        description: |
          The contract type of the job.
      - name: industry
        description: |
          The industry or sector of the company.
      - name: remote
        description: |
          The remote policy of the job.
      - name: text
        description: |
          The text description of the job.
        tests:
          - unique
          - not_null

  - name: stg_urls
    description: |
      The `stg_urls` model contains transformed urls.
    columns:
      - name: id
        description: |
          The primary key for stg_urls.
        tests:
          - unique
          - not_null
      - name: cleaned_url
        description: |
          The url without the part used when a website reposts the same job with a different url.
        tests:
          - unique
          - not_null

  - name: stg_titles
    description: |
      The `stg_titles` model contains transformed job titles.
    columns:
      - name: id
        description: |
          The primary key for stg_titles.
        tests:
          - unique
          - not_null
      - name: title
        description: |
          The original, raw title.
        tests:
          - not_null
      - name: minus_parenthesis
        description: |
          The title without any parenthesis (and what's inside).
        tests:
          - not_null
      - name: minus_gender
        description: |
          The title without gender info that wasn't inside parenthesis.
        tests:
          - not_null

  - name: stg_contract_types
    description: |
      The `stg_contract_types` model contains uniform contract types.
    columns:
      - name: id
        description: |
          The primary key for stg_contract_types.
        tests:
          - unique
          - not_null
      - name: contract
        description: |
          The original, raw contract type.
      - name: simplified_contract
        description: |
          The contract types regrouped into uniform categories.
        tests:
          - accepted_values:
              values: ['Full Time', 'Graduate program', 'Other', 'Freelance']

  - name: stg_remote_policies
    description: |
      The `stg_remote_policies` model contains uniform remote policies.
    columns:
      - name: id
        description: |
          The primary key for stg_remote_policies.
        tests:
          - unique
          - not_null
      - name: remote
        description: |
          The original, raw remote policy.
      - name: simplified_remote
        description: |
          The remote policies regrouped into uniform categories.
        tests:
          - accepted_values:
              values: ['total', 'partial', 'ponctual']

  - name: stg_texts
    description: |
      The `stg_texts` model contains the description of jop postings.
    columns:
      - name: id
        description: |
          The primary key for stg_texts.
        tests:
          - unique
          - not_null
      - name: text
        description: |
          The original, raw text description.
      - name: cleaned_text
        description: |
          The text unique instead of multiple newlines.
        tests:
          - not_null
